### ISSUE TITLE
RT-K3 384 软件中心一直更新中

### ISSUE THREAD

**Issue by HanaForward** [koolshare/armsoft#33]
严重错误:
GET http://192.168.0.1/_api/soft?_=1593263730719 net::ERR_CONNECTION_RESET
无法获取云端app列表导致无法完成初始化
异常错误:
Module_Softcenter.asp:617 Uncaught ReferenceError: tabtitle is not defined
数组没有定义就直接使用

**Comment by HanaForward** [comment]
check_xss_blacklist: /www/Module_Softsetting.asp is not in www
check_xss_blacklist: /www/Module_Softcenter.asp is not in www

**Comment by sadoneli** [comment]
koolshare软件中心并不支持K3
