### ISSUE TITLE
求一个frps

### ISSUE THREAD

**Issue by JasperWong** [koolshare/armsoft#5]
求一个frps

**Comment by ljcbaby** [comment]
好像现在已经有了，要不要Close这个issue？

**Comment by JasperWong** [comment]
没有吧,现在的是frpc

**Comment by ljcbaby** [comment]
记错了，380里有，384里没看到
（自己写一下配置文件就行了吧，又不难

**Comment by quericy** [comment]
我fork出来打了个包: https://github.com/ppyTeam/armsoft/blob/master/frps/frps.tar.gz
版本是frps 0.20.0

最新版分支是 https://github.com/ppyTeam/armsoft/blob/hotfix/latest_frps/frps/frps.tar.gz
frps文件有点大, 10.9MB .....

**Comment by ljcbaby** [comment]
文件大的话可以用upx压缩一下
[使用UPX压缩二进制文件 - Starx's Home](https://www.ioflow.xyz/archives/shi-yong-upx-ya-suo-er-jin-zhi-wen-jian/)

**Comment by quericy** [comment]
> 文件大的话可以用upx压缩一下
> [使用UPX压缩二进制文件 - Starx's Home](https://www.ioflow.xyz/archives/shi-yong-upx-ya-suo-er-jin-zhi-wen-jian/)

@ljcbaby  感谢分享,回去试一下.  
如果在本机设备上压缩,需要配置适用于arm平台的交叉编译参数么?

**Comment by ljcbaby** [comment]
没试过，也是看别人的




------------------&nbsp;Original&nbsp;------------------

**Comment by quericy** [comment]
已更新,压到4MB

https://github.com/ppyTeam/armsoft/blob/hotfix/latest_frps/frps/frps.tar.gz

**Comment by JasperWong** [comment]
> 已更新,压到4MB
> 
> https://github.com/ppyTeam/armsoft/blob/hotfix/latest_frps/frps/frps.tar.gz

谢谢
